export const cars = [
    {
        id: 1,
        name: 'Toyota',
        price: 440,
        year: 2011,
        member: 4,
        type: 'Camry',
        range: 6.1,
        mode: 'automatic',
        images: 'https://www.toyota.com.vn//Resources/Images/F8B33019CF708D9157E8B8F633DDB447.png',
    },
    {
        id: 2,
        name: 'Honda',
        price: 520,
        year: 2015,
        member: 5,
        type: 'Sedan',
        range: 8.3,
        mode: 'automatic',
        images: 'https://autopro8.mediacdn.vn/thumb_w/640/2014/2015-honda-civic-coupe-and-sedan-pricing-announced_1-72e03.jpg',
      },
      {
        id: 3,
        name: 'Ford',
        price: 600,
        year: 2018,
        member: 7,
        type: 'SUV',
        range: 9.5,
        mode: 'automatic',
        images: 'https://thanhnien.mediacdn.vn/uploaded/chicuong/2017_02_08/expedition/2018-ford-expedition-1-1_UVYF.jpg?width=600',
      },
      {
        id: 4,
        name: 'Chevrolet',
        price: 480,
        year: 2016,
        member: 5,
        type: 'Coupe',
        range: 7.8,
        mode: 'automatic',
        images: 'https://cdn.oto360.net/images/car/chevrolet/aveo_icon.webp',
      },
      {
        id: 5,
        name: 'Hyundai',
        price: 550,
        year: 2017,
        member: 5,
        type: 'Hatchback',
        range: 8.2,
        mode: 'automatic',
        images: 'https://hyundaivn.vn/wp-content/uploads/2023/09/hyundai-palisade-hyundaisg-10.png',
      },
      {
        id: 6,
        name: 'Nissan',
        price: 590,
        year: 2019,
        member: 5,
        type: 'Crossover',
        range: 8.9,
        mode: 'automatic',
        images: 'https://daily-nissan.com/wp-content/uploads/2022/11/Kicks-V-Cao-Cap.jpg',
      },
]